  - name: 'Install php-mysql my-sql server pip3'
    apt:
      name:
        - 'mysql-server'
        - 'php-mysql'
        - 'python3-pip'
      state: 'present'
      update_cache: true
    become: true

  - name: pymysql present task
    pip:
      name: 'pymysql'
      state: 'present'
    become: true

  - name: 'Create a new database with name {{ mysql_db_name }}'
    mysql_db:
      name: '{{ mysql_db_name }}'
      login_unix_socket: '{{ mysql_unix_socket_path }}'
      #check_implicit_admin: true
      state: 'present'
    become: true

  
  - name: 'Create a user {{ mysql_username }} for {{ mysql_db_name }} with all database privileges'
    mysql_user:
      name: '{{ mysql_username }}'
      login_unix_socket: /var/run/mysqld/mysqld.sock
      host: localhost
      password: '{{ wordpress_user_password }}'
      priv: '{{ mysql_db_name }}.*:ALL,GRANT'
      state: present
    become: true
    #notify: 'Restart mysql'


  - name: Copy .my.cnf file with root password credentials
    become: true
    become_user: root
    template: src=roles/mysql/templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600
